"""add durable editorial decisions"""

revision = '1836e7c14dde'
down_revision = 'b6f8dccd64e2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editorial_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rewrite_allowed', sa.Boolean(), nullable=False),
    sa.Column('reason_codes', sa.String(), nullable=False),
    sa.Column('protected_entities', sa.String(), nullable=False),
    sa.Column('sentiment', sa.String(length=32), nullable=False),
    sa.Column('framing', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status <> 'REJECT' OR rewrite_allowed = false", name='ck_editorial_reject_disables_rewrite'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_key')
    )
    op.create_table('rewrite_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_key', sa.String(length=255), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_key'),
    sa.UniqueConstraint('idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rewrite_jobs')
    op.drop_table('editorial_decisions')
    # ### end Alembic commands ###
