"""create telegram ingestion schema"""

revision = "b6f8dccd64e2"
down_revision = None
branch_labels = None
depends_on = None

import sqlalchemy as sa

from alembic import op


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_revisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_key", sa.String(length=255), nullable=False),
        sa.Column("editorial_status", sa.String(length=32), nullable=False),
        sa.Column("rewrite_allowed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "editorial_status <> 'REJECT' OR rewrite_allowed = false",
            name="ck_rejected_revision_disables_rewrite",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_key"),
    )
    op.create_table(
        "incoming_posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_account_id", sa.String(length=100), nullable=False),
        sa.Column("donor_channel_id", sa.String(length=100), nullable=False),
        sa.Column("telegram_message_id", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "telegram_account_id",
            "donor_channel_id",
            "telegram_message_id",
            name="uq_incoming_posts_source_identity",
        ),
    )
    op.create_index(
        op.f("ix_incoming_posts_donor_channel_id"),
        "incoming_posts",
        ["donor_channel_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incoming_posts_telegram_account_id"),
        "incoming_posts",
        ["telegram_account_id"],
        unique=False,
    )
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_key", sa.String(length=255), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_table(
        "telegram_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("telegram_user_id", sa.Integer(), nullable=False),
        sa.Column("encrypted_session", sa.String(), nullable=False),
        sa.Column("health_status", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("telegram_user_id"),
    )
    op.create_table(
        "donor_channels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_account_id", sa.Integer(), nullable=False),
        sa.Column("telegram_channel_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["telegram_account_id"],
            ["telegram_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_account_id", "telegram_channel_id"),
    )
    op.create_table(
        "incoming_post_revisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("incoming_post_id", sa.Integer(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("source_text", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["incoming_post_id"], ["incoming_posts.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "incoming_post_id", "revision_number", name="uq_revision_number_per_post"
        ),
    )
    op.create_index(
        op.f("ix_incoming_post_revisions_incoming_post_id"),
        "incoming_post_revisions",
        ["incoming_post_id"],
        unique=False,
    )
    op.create_table(
        "output_channels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_account_id", sa.Integer(), nullable=False),
        sa.Column("telegram_channel_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["telegram_account_id"],
            ["telegram_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_account_id", "telegram_channel_id"),
    )
    op.create_table(
        "channel_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("donor_channel_id", sa.Integer(), nullable=False),
        sa.Column("output_channel_id", sa.Integer(), nullable=False),
        sa.Column("intake_percent", sa.Integer(), nullable=False),
        sa.Column("target_mix_percent", sa.Integer(), nullable=False),
        sa.CheckConstraint("intake_percent BETWEEN 0 AND 100"),
        sa.CheckConstraint("target_mix_percent BETWEEN 0 AND 100"),
        sa.ForeignKeyConstraint(
            ["donor_channel_id"],
            ["donor_channels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["output_channel_id"],
            ["output_channels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("donor_channel_id", "output_channel_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("channel_mappings")
    op.drop_table("output_channels")
    op.drop_index(
        op.f("ix_incoming_post_revisions_incoming_post_id"), table_name="incoming_post_revisions"
    )
    op.drop_table("incoming_post_revisions")
    op.drop_table("donor_channels")
    op.drop_table("telegram_accounts")
    op.drop_table("outbox_events")
    op.drop_index(op.f("ix_incoming_posts_telegram_account_id"), table_name="incoming_posts")
    op.drop_index(op.f("ix_incoming_posts_donor_channel_id"), table_name="incoming_posts")
    op.drop_table("incoming_posts")
    op.drop_table("content_revisions")
    # ### end Alembic commands ###
